# Generated by Django 5.2.1 on 2025-05-29 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatepassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('gatepass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gatepass.gatepassrequest')),
            ],
        ),
    ]
