# Generated by Django 5.2.1 on 2025-05-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0003_gatepassitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
