# Generated by Django 5.2.1 on 2025-05-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0004_gatepassitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassitem',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
